# Generated by Django 4.2.5 on 2023-09-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Item',
        ),
    ]
